apiVersion: v1
kind: Service
metadata:
  name: productivity-backend-service
spec:
  selector:
    app: productivity-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: NodePort