name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Build and push Docker images
        run: |
          docker build -t frontend:latest vaji123/sample:sample14
          docker build -t ${{ secrets.DOCKER_REGISTRY }}vaji123/sample:sample13
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin ${{ secrets.DOCKER_REGISTRY }}
          docker push ${{ secrets.DOCKER_REGISTRY }}/frontend:latest
          docker push ${{ secrets.DOCKER_REGISTRY }}/backend:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/frontend-deployment.yaml
          kubectl apply -f kubernetes/backend-deployment.yaml
