name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Build and push Docker images
        run: |
          docker build -t d0fac12a8b49 ./frontend
          docker build -t bc7e3a44bde5 ./backend

          echo "${{ secrets.Octalite1234 }}" | docker login -u "${{ secrets.vaji123 }}" --password-stdin docker.io
    
          docker tag frontend-image ${{ secrets.DOCKER_REGISTRY }}/frontend:latest
          docker tag backend-image ${{ secrets.DOCKER_REGISTRY }}/backend:latest

          docker push ${{ secrets.DOCKER_REGISTRY }}/frontend:latest
          docker push ${{ secrets.DOCKER_REGISTRY }}/backend:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/frontend-deployment.yaml
          kubectl apply -f kubernetes/backend-deployment.yaml
